version: "3.8"

services:
  marimo:
    build: .
    ports:
      - "2718:2718"
    volumes:
      - .:/app
    command: marimo run seu_notebook.py --host localhost --port 2718

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=localhost --port=8888 --no-browser --allow-root --NotebookApp.token=''